// Generated by CoffeeScript 1.10.0
(function() {
  var exist, fs, getNewFilePath, logObjLength, pick, transifexify, transifexifyAll;

  fs = require('fs');

  pick = require('lodash.pick');

  require('colors');

  exist = function(obj) {
    return obj != null;
  };

  logObjLength = function(label, obj) {
    return console.log(label, Object.keys(obj).length.toString().grey);
  };

  getNewFilePath = function(filePath) {
    return filePath.replace('.json', '') + '.transifex.json';
  };

  transifexify = function(filePath) {
    var newFilePath, obj, text, transifexCompatibleObj;
    if (filePath == null) {
      throw new Error('missing file argument');
    }
    text = fs.readFileSync(filePath, 'utf-8');
    obj = JSON.parse(text);
    logObjLength('src file keys:', obj);
    transifexCompatibleObj = pick(obj, exist);
    logObjLength('tx file keys:', transifexCompatibleObj);
    newFilePath = getNewFilePath(filePath);
    fs.writeFileSync(newFilePath, JSON.stringify(transifexCompatibleObj, null, 4));
    return console.log('done!'.green, newFilePath);
  };

  transifexifyAll = function(filesPaths) {
    return filesPaths.forEach(transifexify);
  };

  module.exports = transifexifyAll;

}).call(this);
